services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tstuser
      - POSTGRES_PASSWORD=tstpw
      - POSTGRES_DB=tstdb
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  database:
