services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://tstuser:tstpw@db:5432/tstdb
    volumes:
      - ./Cargo.lock:/app/Cargo.lock
      - ./Cargo.toml:/app/Cargo.toml
      - ./src:/app/src
      - ./edb_orm/:/app/edb_orm
      - ./index.html:/app/.index.html
      # TODO template files
      - ./cargo-cache:/usr/local/cargo/registry
    command: cargo watch -x run

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tstuser
      - POSTGRES_PASSWORD=tstpw
      - POSTGRES_DB=tstdb
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  cargo-cache:
  database:
